# Generated by Django 5.2.1 on 2025-06-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sets',
            new_name='Set',
        ),
    ]
