# Generated by Django 5.2.1 on 2025-06-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0003_alter_film_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='films', to='sets.set'),
        ),
    ]
